insert into allergy (patient_id, allergy_name, severity, notes) values (17861, 'Shellfish', 'Moderate', 'Donec posuere metus vitae ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2957, 'Pollen', 'Life-threatening', 'Mauris ullamcorper purus sit amet nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7688, 'Shellfish', 'High', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10391, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (2755, 'Aspirin', 'Life-threatening', 'Integer ac leo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1380, 'Pollen', 'Low', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12223, 'Penicillin', 'Life-threatening', 'In congue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18271, 'Penicillin', 'High', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5691, 'Aspirin', 'Low', 'Curabitur at ipsum ac tellus semper interdum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14249, 'Pollen', 'Moderate', 'Aliquam erat volutpat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (359, 'Pollen', 'Low', 'Donec posuere metus vitae ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2189, 'Aspirin', 'Moderate', 'Integer a nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14796, 'Pollen', 'High', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13584, 'Aspirin', 'Moderate', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11189, 'Penicillin', 'Low', 'Nunc purus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2657, 'Peanuts', 'Moderate', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6827, 'Latex', 'Life-threatening', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4451, 'Peanuts', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (17470, 'Shellfish', 'Life-threatening', 'Donec quis orci eget orci vehicula condimentum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15699, 'Latex', 'High', 'Etiam pretium iaculis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14368, 'Peanuts', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (19913, 'Aspirin', 'Life-threatening', 'Donec posuere metus vitae ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15252, 'Penicillin', 'Low', 'Morbi non quam nec dui luctus rutrum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (998, 'Pollen', 'Moderate', 'In eleifend quam a odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5514, 'Penicillin', 'Low', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14869, 'Pollen', 'High', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into allergy (patient_id, allergy_name, severity, notes) values (34, 'Pollen', 'High', 'Etiam pretium iaculis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16584, 'Penicillin', 'Low', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15765, 'Penicillin', 'Moderate', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10491, 'Shellfish', 'Low', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2231, 'Peanuts', 'Life-threatening', 'Ut at dolor quis odio consequat varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6040, 'Aspirin', 'Moderate', 'Donec posuere metus vitae ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16929, 'Shellfish', 'Low', 'In congue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2009, 'Aspirin', 'Life-threatening', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18857, 'Shellfish', 'Life-threatening', 'Duis bibendum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2873, 'Aspirin', 'Life-threatening', 'Morbi non lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15557, 'Shellfish', 'High', 'Morbi a ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19235, 'Peanuts', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (7269, 'Penicillin', 'Life-threatening', 'Suspendisse accumsan tortor quis turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2854, 'Aspirin', 'Moderate', 'Nullam porttitor lacus at turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19535, 'Latex', 'Life-threatening', 'Etiam pretium iaculis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13161, 'Latex', 'Moderate', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14589, 'Penicillin', 'Low', 'Nunc purus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4875, 'Latex', 'Moderate', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15738, 'Penicillin', 'High', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1150, 'Shellfish', 'Low', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2666, 'Shellfish', 'Low', 'Nulla tempus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2945, 'Aspirin', 'Low', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9798, 'Pollen', 'Low', 'Curabitur at ipsum ac tellus semper interdum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13801, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12383, 'Penicillin', 'High', 'Aliquam erat volutpat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10353, 'Pollen', 'Low', 'Fusce consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4620, 'Pollen', 'Low', 'Sed ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (389, 'Peanuts', 'Life-threatening', 'Nunc nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8960, 'Latex', 'Life-threatening', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1311, 'Penicillin', 'Life-threatening', 'Nam dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17969, 'Latex', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6146, 'Penicillin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (17600, 'Aspirin', 'Life-threatening', 'Morbi non lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5089, 'Shellfish', 'Life-threatening', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16014, 'Pollen', 'Life-threatening', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (351, 'Shellfish', 'High', 'Pellentesque at nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15452, 'Aspirin', 'Low', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17896, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16016, 'Shellfish', 'Moderate', 'Donec dapibus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12136, 'Penicillin', 'Moderate', 'Praesent id massa id nisl venenatis lacinia.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6532, 'Shellfish', 'Low', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8332, 'Latex', 'Moderate', 'Vivamus vestibulum sagittis sapien.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19896, 'Pollen', 'Life-threatening', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9694, 'Latex', 'Low', 'Donec quis orci eget orci vehicula condimentum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5894, 'Peanuts', 'Low', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17402, 'Shellfish', 'Low', 'Pellentesque at nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9813, 'Shellfish', 'Moderate', 'Maecenas pulvinar lobortis est.');
insert into allergy (patient_id, allergy_name, severity, notes) values (800, 'Penicillin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16320, 'Aspirin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (15073, 'Pollen', 'Low', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8678, 'Aspirin', 'Moderate', 'Quisque ut erat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13549, 'Penicillin', 'Life-threatening', 'Cras non velit nec nisi vulputate nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1788, 'Peanuts', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12820, 'Aspirin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (14844, 'Pollen', 'Moderate', 'Vestibulum rutrum rutrum neque.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19277, 'Aspirin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (13571, 'Latex', 'Life-threatening', 'Pellentesque at nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10031, 'Latex', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11436, 'Peanuts', 'Moderate', 'In eleifend quam a odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13138, 'Penicillin', 'High', 'Nunc rhoncus dui vel sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12203, 'Peanuts', 'Low', 'In blandit ultrices enim.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15997, 'Aspirin', 'Low', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9526, 'Aspirin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11472, 'Aspirin', 'Moderate', 'Vivamus vestibulum sagittis sapien.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4707, 'Aspirin', 'High', 'Cras non velit nec nisi vulputate nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17979, 'Latex', 'High', 'Mauris ullamcorper purus sit amet nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17443, 'Peanuts', 'Low', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19974, 'Latex', 'Moderate', 'Aliquam non mauris.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19100, 'Pollen', 'Moderate', 'Integer tincidunt ante vel ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7038, 'Peanuts', 'Low', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8778, 'Aspirin', 'Low', 'Aenean sit amet justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4045, 'Peanuts', 'High', 'Phasellus id sapien in sapien iaculis congue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4737, 'Peanuts', 'Moderate', 'Proin at turpis a pede posuere nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7661, 'Penicillin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12505, 'Shellfish', 'High', 'Pellentesque viverra pede ac diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9080, 'Shellfish', 'Life-threatening', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5853, 'Latex', 'Moderate', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8773, 'Latex', 'Low', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17776, 'Shellfish', 'Moderate', 'Duis at velit eu est congue elementum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7637, 'Pollen', 'Moderate', 'Etiam pretium iaculis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15336, 'Penicillin', 'Life-threatening', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11365, 'Shellfish', 'High', 'Nunc nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16829, 'Latex', 'High', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2752, 'Pollen', 'Moderate', 'Nam nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2768, 'Latex', 'Low', 'Vivamus tortor.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6965, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (5935, 'Aspirin', 'Low', 'Integer ac neque.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18126, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (18028, 'Aspirin', 'Moderate', 'Nam tristique tortor eu pede.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14326, 'Latex', 'Life-threatening', 'Nulla suscipit ligula in lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14977, 'Aspirin', 'High', 'Sed accumsan felis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16191, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (8153, 'Peanuts', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6050, 'Pollen', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12198, 'Shellfish', 'Moderate', 'Maecenas rhoncus aliquam lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9087, 'Aspirin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3982, 'Peanuts', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16622, 'Shellfish', 'Moderate', 'Duis ac nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9627, 'Aspirin', 'Low', 'Donec dapibus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19405, 'Shellfish', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (254, 'Aspirin', 'High', 'Nulla tellus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8260, 'Aspirin', 'Moderate', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into allergy (patient_id, allergy_name, severity, notes) values (518, 'Shellfish', 'Low', 'Donec dapibus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16948, 'Pollen', 'Moderate', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10572, 'Peanuts', 'Life-threatening', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3982, 'Penicillin', 'Life-threatening', 'Nulla facilisi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8119, 'Shellfish', 'Low', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4060, 'Shellfish', 'High', 'Nulla justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17652, 'Latex', 'Low', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8616, 'Pollen', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (944, 'Peanuts', 'Life-threatening', 'Integer tincidunt ante vel ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14702, 'Latex', 'Low', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14639, 'Aspirin', 'Life-threatening', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (577, 'Pollen', 'Low', 'Suspendisse potenti.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13079, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (7588, 'Latex', 'Life-threatening', 'Donec quis orci eget orci vehicula condimentum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14985, 'Shellfish', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (9869, 'Penicillin', 'Moderate', 'Nullam varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8220, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (18217, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12387, 'Pollen', 'Low', 'Sed sagittis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1314, 'Peanuts', 'Low', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16040, 'Shellfish', 'Life-threatening', 'Nulla justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2799, 'Peanuts', 'High', 'Nulla ac enim.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2249, 'Pollen', 'Low', 'Vestibulum rutrum rutrum neque.');
insert into allergy (patient_id, allergy_name, severity, notes) values (806, 'Aspirin', 'Life-threatening', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16744, 'Penicillin', 'Moderate', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8578, 'Aspirin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6982, 'Latex', 'Low', 'Etiam vel augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4625, 'Latex', 'Low', 'Praesent id massa id nisl venenatis lacinia.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14532, 'Peanuts', 'Moderate', 'Morbi ut odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3864, 'Peanuts', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (10546, 'Peanuts', 'Low', 'Duis at velit eu est congue elementum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14642, 'Aspirin', 'Moderate', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16348, 'Peanuts', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (15958, 'Shellfish', 'High', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13739, 'Shellfish', 'Moderate', 'Donec posuere metus vitae ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9976, 'Latex', 'High', 'Vivamus tortor.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9731, 'Shellfish', 'High', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4658, 'Latex', 'High', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19296, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (8679, 'Shellfish', 'High', 'Donec ut dolor.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3386, 'Shellfish', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (1307, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (15648, 'Shellfish', 'High', 'Integer ac neque.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10157, 'Pollen', 'Moderate', 'Nunc nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10479, 'Latex', 'Life-threatening', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17683, 'Pollen', 'Moderate', 'Nulla justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17408, 'Peanuts', 'High', 'Morbi non quam nec dui luctus rutrum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19785, 'Pollen', 'Moderate', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11393, 'Pollen', 'Moderate', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13521, 'Pollen', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16901, 'Pollen', 'Life-threatening', 'Sed ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4711, 'Pollen', 'Low', 'Suspendisse accumsan tortor quis turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12929, 'Penicillin', 'Moderate', 'Morbi porttitor lorem id ligula.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4394, 'Latex', 'Low', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1788, 'Shellfish', 'Low', 'Vivamus vestibulum sagittis sapien.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18661, 'Aspirin', 'Low', 'Curabitur in libero ut massa volutpat convallis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5747, 'Pollen', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (10316, 'Aspirin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3053, 'Pollen', 'Life-threatening', 'Donec ut mauris eget massa tempor convallis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7266, 'Peanuts', 'Low', 'Nullam varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1800, 'Shellfish', 'Moderate', 'Nam tristique tortor eu pede.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11085, 'Aspirin', 'Low', 'Fusce posuere felis sed lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11823, 'Pollen', 'Low', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12763, 'Aspirin', 'High', 'Duis bibendum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (15529, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (5467, 'Latex', 'Life-threatening', 'Curabitur gravida nisi at nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11904, 'Pollen', 'Low', 'Integer ac leo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7108, 'Aspirin', 'Life-threatening', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (654, 'Latex', 'Moderate', 'Fusce posuere felis sed lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1203, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (4450, 'Peanuts', 'Moderate', 'Nunc purus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16480, 'Aspirin', 'Life-threatening', 'Morbi ut odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19015, 'Aspirin', 'High', 'Aenean auctor gravida sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1850, 'Shellfish', 'Low', 'Duis ac nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14979, 'Aspirin', 'High', 'Etiam pretium iaculis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16495, 'Peanuts', 'Low', 'Pellentesque viverra pede ac diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2663, 'Latex', 'High', 'Morbi non lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12868, 'Aspirin', 'Moderate', 'Morbi non quam nec dui luctus rutrum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13504, 'Latex', 'Life-threatening', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10582, 'Penicillin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6969, 'Pollen', 'High', 'Morbi non quam nec dui luctus rutrum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8631, 'Shellfish', 'Low', 'Nam nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4391, 'Latex', 'High', 'Nullam porttitor lacus at turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3144, 'Shellfish', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12326, 'Aspirin', 'Low', 'Mauris ullamcorper purus sit amet nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12272, 'Pollen', 'Moderate', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13161, 'Latex', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (19100, 'Peanuts', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (426, 'Shellfish', 'High', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14541, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3947, 'Peanuts', 'Moderate', 'Mauris ullamcorper purus sit amet nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4229, 'Shellfish', 'Low', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16310, 'Pollen', 'Life-threatening', 'Ut at dolor quis odio consequat varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18404, 'Latex', 'Life-threatening', 'Donec semper sapien a libero.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9685, 'Latex', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (7838, 'Peanuts', 'Life-threatening', 'Nam dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8110, 'Aspirin', 'Life-threatening', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14393, 'Latex', 'Moderate', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13250, 'Latex', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (9925, 'Pollen', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (14048, 'Penicillin', 'High', 'Pellentesque at nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6441, 'Latex', 'Low', 'Nulla justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9311, 'Latex', 'Life-threatening', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1018, 'Penicillin', 'Life-threatening', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18302, 'Peanuts', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (2570, 'Pollen', 'High', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3175, 'Pollen', 'Moderate', 'Fusce posuere felis sed lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4881, 'Latex', 'High', 'Etiam justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8045, 'Latex', 'High', 'Maecenas pulvinar lobortis est.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2081, 'Peanuts', 'Life-threatening', 'Fusce consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16344, 'Shellfish', 'High', 'Praesent blandit lacinia erat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11166, 'Latex', 'Low', 'Donec ut dolor.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14465, 'Penicillin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (15245, 'Latex', 'Life-threatening', 'Maecenas tincidunt lacus at velit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10789, 'Aspirin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11430, 'Pollen', 'Moderate', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12336, 'Penicillin', 'Life-threatening', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4363, 'Pollen', 'Low', 'Cras pellentesque volutpat dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (291, 'Penicillin', 'Moderate', 'Morbi non quam nec dui luctus rutrum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (257, 'Peanuts', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16701, 'Aspirin', 'Moderate', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11217, 'Peanuts', 'Low', 'Proin risus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13316, 'Pollen', 'Moderate', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17652, 'Pollen', 'High', 'In quis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12688, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3622, 'Shellfish', 'Low', 'Suspendisse potenti.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6022, 'Pollen', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11915, 'Aspirin', 'Low', 'Nullam porttitor lacus at turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5238, 'Shellfish', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11495, 'Shellfish', 'High', 'Mauris lacinia sapien quis libero.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5811, 'Penicillin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (10985, 'Penicillin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (498, 'Aspirin', 'Moderate', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16074, 'Peanuts', 'Moderate', 'Nulla mollis molestie lorem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5348, 'Pollen', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (1381, 'Latex', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6146, 'Shellfish', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (5791, 'Aspirin', 'Low', 'Aenean fermentum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7678, 'Pollen', 'Moderate', 'Ut tellus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19144, 'Shellfish', 'Low', 'Suspendisse potenti.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19077, 'Penicillin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11625, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16726, 'Latex', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (5116, 'Aspirin', 'Life-threatening', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9251, 'Shellfish', 'Moderate', 'Etiam vel augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2359, 'Penicillin', 'Low', 'Mauris lacinia sapien quis libero.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16809, 'Shellfish', 'High', 'Cras in purus eu magna vulputate luctus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10631, 'Latex', 'Life-threatening', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18217, 'Pollen', 'High', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12585, 'Shellfish', 'Low', 'Suspendisse potenti.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9840, 'Peanuts', 'Low', 'Mauris lacinia sapien quis libero.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2188, 'Shellfish', 'Life-threatening', 'Sed sagittis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1141, 'Latex', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6275, 'Peanuts', 'Life-threatening', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16400, 'Latex', 'Low', 'Vestibulum sed magna at nunc commodo placerat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12380, 'Shellfish', 'Low', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5077, 'Aspirin', 'High', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2686, 'Latex', 'Low', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9748, 'Pollen', 'High', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18954, 'Penicillin', 'High', 'Cras pellentesque volutpat dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10081, 'Latex', 'Life-threatening', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (654, 'Pollen', 'High', 'Ut tellus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10744, 'Shellfish', 'Moderate', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10235, 'Peanuts', 'High', 'Aenean auctor gravida sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10162, 'Penicillin', 'Low', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4769, 'Pollen', 'High', 'Cras in purus eu magna vulputate luctus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12833, 'Pollen', 'Life-threatening', 'Duis ac nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7474, 'Aspirin', 'Low', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8191, 'Pollen', 'Life-threatening', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17635, 'Shellfish', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (1822, 'Penicillin', 'Low', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5685, 'Pollen', 'High', 'Nulla nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4316, 'Penicillin', 'High', 'Fusce posuere felis sed lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2781, 'Latex', 'Low', 'Etiam pretium iaculis justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8285, 'Shellfish', 'High', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8311, 'Shellfish', 'Life-threatening', 'Pellentesque at nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7209, 'Pollen', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (14020, 'Latex', 'Moderate', 'Vivamus tortor.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7111, 'Penicillin', 'Low', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8853, 'Aspirin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (5661, 'Penicillin', 'Life-threatening', 'Nunc rhoncus dui vel sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3522, 'Latex', 'Low', 'Ut tellus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18968, 'Shellfish', 'Low', 'Mauris sit amet eros.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6937, 'Latex', 'Moderate', 'Phasellus id sapien in sapien iaculis congue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13479, 'Shellfish', 'Low', 'Sed ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19296, 'Shellfish', 'Moderate', 'Mauris sit amet eros.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19219, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (700, 'Penicillin', 'Low', 'In congue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13100, 'Aspirin', 'Life-threatening', 'Donec ut mauris eget massa tempor convallis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4580, 'Shellfish', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (4586, 'Latex', 'High', 'Etiam faucibus cursus urna.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2829, 'Latex', 'Moderate', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11451, 'Latex', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (10530, 'Aspirin', 'High', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3896, 'Aspirin', 'Moderate', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10308, 'Pollen', 'Low', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5824, 'Latex', 'Low', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6026, 'Aspirin', 'Moderate', 'Fusce consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18958, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (8271, 'Pollen', 'High', 'Duis mattis egestas metus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3496, 'Latex', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3249, 'Penicillin', 'High', 'Suspendisse potenti.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16290, 'Peanuts', 'Moderate', 'Proin at turpis a pede posuere nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13806, 'Latex', 'Moderate', 'Morbi porttitor lorem id ligula.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14764, 'Shellfish', 'Life-threatening', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11523, 'Pollen', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (9111, 'Aspirin', 'Life-threatening', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8531, 'Peanuts', 'Life-threatening', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1126, 'Shellfish', 'Low', 'Nunc nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12145, 'Aspirin', 'High', 'Duis aliquam convallis nunc.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14901, 'Penicillin', 'Moderate', 'Aenean sit amet justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4133, 'Aspirin', 'Moderate', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14505, 'Shellfish', 'High', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3046, 'Peanuts', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (5994, 'Pollen', 'Moderate', 'Quisque ut erat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8844, 'Latex', 'Moderate', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11453, 'Latex', 'Moderate', 'Cras non velit nec nisi vulputate nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12599, 'Penicillin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (8340, 'Peanuts', 'Moderate', 'Donec dapibus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9687, 'Shellfish', 'Low', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4333, 'Shellfish', 'Low', 'Sed accumsan felis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13434, 'Shellfish', 'Life-threatening', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2998, 'Pollen', 'Low', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5736, 'Latex', 'Low', 'Pellentesque eget nunc.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17658, 'Aspirin', 'Moderate', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4026, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (7057, 'Latex', 'Moderate', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5136, 'Penicillin', 'High', 'Ut tellus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1876, 'Pollen', 'Low', 'Donec quis orci eget orci vehicula condimentum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5267, 'Shellfish', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (1646, 'Shellfish', 'Low', 'Duis bibendum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (806, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (14196, 'Shellfish', 'Life-threatening', 'Nulla facilisi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9910, 'Pollen', 'Low', 'Aliquam erat volutpat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5065, 'Peanuts', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (18968, 'Pollen', 'Low', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9763, 'Aspirin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6468, 'Shellfish', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (17356, 'Latex', 'Moderate', 'In sagittis dui vel nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2458, 'Peanuts', 'Low', 'Ut at dolor quis odio consequat varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1646, 'Aspirin', 'Low', 'Integer ac leo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13445, 'Peanuts', 'Low', 'Morbi porttitor lorem id ligula.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8735, 'Penicillin', 'High', 'Nunc rhoncus dui vel sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17854, 'Peanuts', 'High', 'Curabitur at ipsum ac tellus semper interdum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12002, 'Peanuts', 'High', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7515, 'Latex', 'Moderate', 'Nunc purus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4253, 'Latex', 'High', 'Donec ut mauris eget massa tempor convallis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12179, 'Latex', 'High', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (593, 'Shellfish', 'Low', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18911, 'Penicillin', 'Life-threatening', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3343, 'Pollen', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (16513, 'Shellfish', 'High', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10091, 'Penicillin', 'Moderate', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1199, 'Peanuts', 'Low', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11551, 'Aspirin', 'Moderate', 'Integer non velit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19396, 'Aspirin', 'Moderate', 'Morbi non lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6922, 'Penicillin', 'Life-threatening', 'Praesent lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13857, 'Aspirin', 'Life-threatening', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4236, 'Aspirin', 'Life-threatening', 'Proin at turpis a pede posuere nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14974, 'Aspirin', 'Moderate', 'Quisque porta volutpat erat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18395, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (19256, 'Pollen', 'Low', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2704, 'Penicillin', 'Life-threatening', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (693, 'Latex', 'Life-threatening', 'Integer a nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16556, 'Pollen', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11391, 'Pollen', 'Low', 'Nulla tempus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10275, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6615, 'Peanuts', 'Life-threatening', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11905, 'Penicillin', 'Life-threatening', 'In congue.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16144, 'Latex', 'Low', 'Quisque porta volutpat erat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11140, 'Pollen', 'Life-threatening', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16195, 'Penicillin', 'Moderate', 'Nam dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8953, 'Shellfish', 'Life-threatening', 'Morbi porttitor lorem id ligula.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3894, 'Aspirin', 'High', 'Quisque porta volutpat erat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13145, 'Penicillin', 'High', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17443, 'Peanuts', 'High', 'Fusce consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9623, 'Aspirin', 'Low', 'Morbi a ipsum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12179, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (7298, 'Shellfish', 'Low', 'Sed sagittis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1784, 'Pollen', 'Low', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17475, 'Pollen', 'Low', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (18367, 'Peanuts', 'High', 'Ut at dolor quis odio consequat varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12036, 'Aspirin', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (4266, 'Shellfish', 'Moderate', 'Morbi ut odio.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2496, 'Peanuts', 'Low', 'Proin risus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6595, 'Aspirin', 'Low', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5872, 'Peanuts', 'Low', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12657, 'Pollen', 'Life-threatening', 'Fusce posuere felis sed lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11105, 'Peanuts', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (17735, 'Latex', 'Low', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4683, 'Pollen', 'Low', 'Suspendisse ornare consequat lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9830, 'Penicillin', 'Low', 'Pellentesque viverra pede ac diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7122, 'Pollen', 'High', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2054, 'Shellfish', 'Low', 'Praesent id massa id nisl venenatis lacinia.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4504, 'Aspirin', 'Low', 'Curabitur in libero ut massa volutpat convallis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9743, 'Pollen', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (14180, 'Pollen', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (1677, 'Aspirin', 'Moderate', 'Vivamus vestibulum sagittis sapien.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17875, 'Pollen', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12368, 'Penicillin', 'Moderate', 'Morbi non lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6237, 'Aspirin', 'Life-threatening', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7523, 'Latex', 'Moderate', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9903, 'Peanuts', 'Moderate', 'Sed accumsan felis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5516, 'Peanuts', 'Low', 'Nam dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10172, 'Aspirin', 'High', 'Nulla suscipit ligula in lacus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13709, 'Shellfish', 'High', 'Praesent id massa id nisl venenatis lacinia.');
insert into allergy (patient_id, allergy_name, severity, notes) values (5012, 'Latex', 'Moderate', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8764, 'Peanuts', 'High', 'Nullam molestie nibh in lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17596, 'Aspirin', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (2260, 'Aspirin', 'Moderate', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7070, 'Shellfish', 'Moderate', 'Duis ac nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1828, 'Penicillin', 'High', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7835, 'Shellfish', 'High', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (12662, 'Penicillin', 'Moderate', 'Suspendisse ornare consequat lectus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19883, 'Latex', 'Low', 'Mauris ullamcorper purus sit amet nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (740, 'Peanuts', 'Moderate', 'Praesent blandit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17683, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (39, 'Shellfish', 'Moderate', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2599, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (19889, 'Peanuts', 'Low', 'Nam tristique tortor eu pede.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6224, 'Pollen', 'Low', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1720, 'Pollen', 'Moderate', 'Nulla ac enim.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3983, 'Pollen', 'Moderate', 'Aliquam erat volutpat.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3589, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (19826, 'Latex', 'Life-threatening', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7655, 'Penicillin', 'Life-threatening', 'Nullam varius.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17488, 'Shellfish', 'Moderate', 'Ut tellus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1504, 'Peanuts', 'Life-threatening', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into allergy (patient_id, allergy_name, severity, notes) values (8841, 'Latex', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3841, 'Penicillin', 'Life-threatening', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9197, 'Aspirin', 'Low', 'Cras pellentesque volutpat dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10145, 'Latex', 'Low', 'Nam nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12731, 'Penicillin', 'Moderate', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13571, 'Peanuts', 'High', 'Nunc rhoncus dui vel sem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6650, 'Penicillin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (10181, 'Latex', 'Low', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17579, 'Pollen', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (14519, 'Pollen', 'Life-threatening', 'Donec vitae nisi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (2566, 'Latex', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (11625, 'Peanuts', 'Life-threatening', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into allergy (patient_id, allergy_name, severity, notes) values (19742, 'Penicillin', 'Life-threatening', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into allergy (patient_id, allergy_name, severity, notes) values (9611, 'Latex', 'Life-threatening', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into allergy (patient_id, allergy_name, severity, notes) values (16711, 'Peanuts', 'High', 'Phasellus in felis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14920, 'Peanuts', 'Low', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1577, 'Aspirin', 'Low', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (3766, 'Pollen', 'Life-threatening', 'Proin at turpis a pede posuere nonummy.');
insert into allergy (patient_id, allergy_name, severity, notes) values (782, 'Shellfish', 'Moderate', 'Pellentesque viverra pede ac diam.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6837, 'Peanuts', 'Low', 'Nulla facilisi.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1917, 'Shellfish', 'High', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13451, 'Peanuts', 'High', 'Curabitur gravida nisi at nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (3791, 'Latex', 'Low', 'Cras pellentesque volutpat dui.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14691, 'Aspirin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (6711, 'Shellfish', 'Moderate', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into allergy (patient_id, allergy_name, severity, notes) values (6751, 'Pollen', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (17752, 'Aspirin', 'Moderate', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into allergy (patient_id, allergy_name, severity, notes) values (10821, 'Aspirin', 'Moderate', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into allergy (patient_id, allergy_name, severity, notes) values (14868, 'Penicillin', 'High', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13922, 'Aspirin', 'Life-threatening', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (2412, 'Peanuts', 'Moderate', null);
insert into allergy (patient_id, allergy_name, severity, notes) values (7354, 'Penicillin', 'Low', 'Nulla justo.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17076, 'Pollen', 'Low', 'In hac habitasse platea dictumst.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12441, 'Aspirin', 'Moderate', 'Nulla mollis molestie lorem.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12788, 'Penicillin', 'High', 'Duis ac nibh.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11443, 'Penicillin', 'Life-threatening', 'Suspendisse potenti.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17994, 'Shellfish', 'Moderate', 'Vivamus tortor.');
insert into allergy (patient_id, allergy_name, severity, notes) values (12451, 'Peanuts', 'High', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (13416, 'Aspirin', 'Life-threatening', 'Aenean fermentum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (17363, 'Penicillin', 'Moderate', 'Pellentesque eget nunc.');
insert into allergy (patient_id, allergy_name, severity, notes) values (1279, 'Aspirin', 'Moderate', 'Duis at velit eu est congue elementum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (4513, 'Penicillin', 'High', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into allergy (patient_id, allergy_name, severity, notes) values (7592, 'Penicillin', 'Life-threatening', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into allergy (patient_id, allergy_name, severity, notes) values (11205, 'Latex', 'Moderate', 'Suspendisse potenti.');
